name: Greeting
# on: push
on: [push, workflow_dispatch]
jobs:
    Run_Test_Cases:
        runs-on: ubuntu-latest
        steps:
            - name: "GetCode"
              uses: actions/checkout@v4
              #run: echo "${{github}}"
            - name: Install node 20
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: print node version
              run: node -v
            - name: Install dependencies
              run: npm ci
            - name: Run test
              run: npm run test
